pub use crate::generated::card_ids::CardId;
pub use crate::generated::relic_ids::RelicId;

crate::string_id_serde!(CardId, sts_id, from_sts_id);
crate::string_id_serde!(RelicId, sts_id, from_sts_id);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Character {
    Ironclad,
    Silent,
    Defect,
    Watcher,
}

crate::string_id_map! {
    Character,
    STS_NAMES,
    sts_name,
    from_sts_name {
        Character::Ironclad => "IRONCLAD" | "IC" | "IRON_CLAD",
        Character::Silent => "THE_SILENT" | "SILENT" | "THE-SILENT",
        Character::Defect => "DEFECT",
        Character::Watcher => "WATCHER",
    }
}

impl Character {
    pub fn oracle_dir(self) -> &'static str {
        match self {
            Character::Ironclad => "ironclad",
            Character::Silent => "silent",
            Character::Defect => "defect",
            Character::Watcher => "watcher",
        }
    }

    pub fn from_cli(s: &str) -> Option<Self> {
        Self::from_sts_name(&s.to_ascii_uppercase())
    }
}

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CardColor {
    RED,
    GREEN,
    BLUE,
    PURPLE,
    COLORLESS,
    CURSE,
}

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CardRarity {
    BASIC,
    COMMON,
    UNCOMMON,
    RARE,
    SPECIAL,
    CURSE,
}

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CardType {
    ATTACK,
    SKILL,
    POWER,
    STATUS,
    CURSE,
}

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CardTarget {
    ENEMY,
    ALL_ENEMY,
    SELF,
    NONE,
    SELF_AND_ENEMY,
    ALL,
}

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RelicTier {
    STARTER,
    COMMON,
    UNCOMMON,
    RARE,
    SHOP,
    BOSS,
    SPECIAL,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PotionRarity {
    COMMON,
    UNCOMMON,
    RARE,
    PLACEHOLDER,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RoomType {
    Monster,
    Elite,
    Event,
    Rest,
    Shop,
    Treasure,
    Boss,
    BossTreasure,
    Victory,
    Neow,
    Empty,
}

crate::string_id_map! {
    RoomType,
    JAVA_CLASSES,
    java_class,
    from_java_class {
        RoomType::Monster => "com.megacrit.cardcrawl.rooms.MonsterRoom",
        RoomType::Elite => "com.megacrit.cardcrawl.rooms.MonsterRoomElite",
        RoomType::Event => "com.megacrit.cardcrawl.rooms.EventRoom",
        RoomType::Rest => "com.megacrit.cardcrawl.rooms.RestRoom",
        RoomType::Shop => "com.megacrit.cardcrawl.rooms.ShopRoom",
        RoomType::Treasure => "com.megacrit.cardcrawl.rooms.TreasureRoom",
        RoomType::Boss => "com.megacrit.cardcrawl.rooms.MonsterRoomBoss",
        RoomType::BossTreasure => "com.megacrit.cardcrawl.rooms.TreasureRoomBoss",
        RoomType::Victory => "com.megacrit.cardcrawl.rooms.VictoryRoom",
        RoomType::Neow => "com.megacrit.cardcrawl.neow.NeowRoom",
        RoomType::Empty => "com.megacrit.cardcrawl.rooms.EmptyRoom",
    }
}

crate::string_id_serde!(RoomType, java_class, from_java_class);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Act {
    Exordium = 1,
    City = 2,
    Beyond = 3,
    Ending = 4,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum EventId {
    AccursedBlacksmith,
    Addict,
    BackToBasics,
    Beggar,
    BigFish,
    BonfireElementals,
    Cleric,
    Colosseum,
    CursedTome,
    DeadAdventurer,
    Designer,
    DrugDealer,
    Duplicator,
    FaceTrader,
    Falling,
    ForgottenAltar,
    FountainOfCleansing,
    Ghosts,
    GoldenIdol,
    GoldenShrine,
    GoldenWing,
    Joust,
    KnowingSkull,
    Lab,
    LiarsGame,
    Library,
    LivingWall,
    MaskedBandits,
    MatchAndKeep,
    Mausoleum,
    MindBloom,
    MoaiHead,
    Mushrooms,
    MysteriousSphere,
    Nest,
    Nloth,
    NoteForYourself,
    Purifier,
    ScrapOoze,
    SecretPortal,
    SensoryStone,
    ShiningLight,
    SpireHeart,
    TombOfLordRedMask,
    Transmorgrifier,
    UpgradeShrine,
    Vampires,
    WeMeetAgain,
    WheelOfChange,
    WindingHalls,
    WomanInBlue,
    WorldOfGoop,
}

crate::string_id_map! {
    EventId,
    STS_IDS,
    sts_id,
    from_sts_id {
        EventId::AccursedBlacksmith => "Accursed Blacksmith",
        EventId::Addict => "Addict",
        EventId::BackToBasics => "Back to Basics",
        EventId::Beggar => "Beggar",
        EventId::BigFish => "Big Fish",
        EventId::BonfireElementals => "Bonfire Elementals",
        EventId::Cleric => "The Cleric",
        EventId::Colosseum => "Colosseum",
        EventId::CursedTome => "Cursed Tome",
        EventId::DeadAdventurer => "Dead Adventurer",
        EventId::Designer => "Designer",
        EventId::DrugDealer => "Drug Dealer",
        EventId::Duplicator => "Duplicator",
        EventId::FaceTrader => "FaceTrader",
        EventId::Falling => "Falling",
        EventId::ForgottenAltar => "Forgotten Altar",
        EventId::FountainOfCleansing => "Fountain of Cleansing",
        EventId::Ghosts => "Ghosts",
        EventId::GoldenIdol => "Golden Idol",
        EventId::GoldenShrine => "Golden Shrine",
        EventId::GoldenWing => "Golden Wing",
        EventId::Joust => "The Joust",
        EventId::KnowingSkull => "Knowing Skull",
        EventId::Lab => "Lab",
        EventId::LiarsGame => "Liars Game",
        EventId::Library => "The Library",
        EventId::LivingWall => "Living Wall",
        EventId::MaskedBandits => "Masked Bandits",
        EventId::MatchAndKeep => "Match and Keep!",
        EventId::Mausoleum => "The Mausoleum",
        EventId::MindBloom => "MindBloom",
        EventId::MoaiHead => "The Moai Head",
        EventId::Mushrooms => "Mushrooms",
        EventId::MysteriousSphere => "Mysterious Sphere",
        EventId::Nest => "Nest",
        EventId::Nloth => "N'loth",
        EventId::NoteForYourself => "NoteForYourself",
        EventId::Purifier => "Purifier",
        EventId::ScrapOoze => "Scrap Ooze",
        EventId::SecretPortal => "SecretPortal",
        EventId::SensoryStone => "SensoryStone",
        EventId::ShiningLight => "Shining Light",
        EventId::SpireHeart => "SpireHeart",
        EventId::TombOfLordRedMask => "Tomb of Lord Red Mask",
        EventId::Transmorgrifier => "Transmorgrifier",
        EventId::UpgradeShrine => "Upgrade Shrine",
        EventId::Vampires => "Vampires",
        EventId::WeMeetAgain => "WeMeetAgain",
        EventId::WheelOfChange => "Wheel of Change",
        EventId::WindingHalls => "Winding Halls",
        EventId::WomanInBlue => "The Woman in Blue" | "Woman in Blue",
        EventId::WorldOfGoop => "World of Goop",
    }
}

crate::string_id_serde!(EventId, sts_id, from_sts_id);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PowerId {
    Strength,
    Dexterity,
    Weak,
    Vulnerable,
    Frail,
    Ritual,
    CurlUp,
    AngerNob,
    Angry,
    Split,
    SharpHide,
    Thievery,
    Flight,
    ModeShift,
    Intangible,
    Buffer,
    Metallicize,
    Combust,
    FlameBarrier,
    Rage,
    LoseStrength,
    FireBreathing,
    Brutality,
    FeelNoPain,
    DemonForm,
    DarkEmbrace,
    Accuracy,
    PenNib,
    NoxiousFumes,
    Poison,
    Constricted,
    SporeCloud,
    FrailPlayer,
    Entangled,
    DrawCard,
    DrawReduction,
    NoDraw,
    Hex,
    Barricade,
    Artifact,
    Malleable,
    PlatedArmor,
    PainfulStabs,
    TheBomb,
    LoseDexterity,
    Thorns,
    Explosive,
    Fading,
    Shackled,
    Slow,
    Curiosity,
    Regen,
    Unawakened,
    Focus,
    Bias,
    Rebound,
    Energized,
    Electro,
    Loop,
    Sadistic,
    SelfRepair,
    EchoForm,
    Heatsink,
    CreativeAI,
    LockOn,
    Storm,
    Amplify,
    NoBlock,
    HelloWorld,
    StaticDischarge,
    Confusion,
    StrengthUp,
    Magnetism,
    Mayhem,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PotionId {
    Slot,
    Block,
    Strength,
    Dexterity,
    Fire,
    Explosive,
    Fear,
    Weak,
    Attack,
    Skill,
    Power,
    Blood,
    Elixir,
    HeartOfIron,
    LiquidBronze,
    Duplication,
    Energy,
    Swift,
    Colorless,
    BlessingOfTheForge,
    FruitJuice,
    Regen,
    Speed,
    Steroid,
    Ancient,
    GamblersBrew,
    EssenceOfSteel,
    DistilledChaos,
    LiquidMemories,
    Cultist,
    SneckoOil,
    Fairy,
    SmokeBomb,
    EntropicBrew,
    Focus,
    PotionOfCapacity,
    EssenceOfDarkness,
}

crate::string_id_map! {
    PotionId,
    STS_IDS,
    sts_id,
    from_sts_id {
        PotionId::Slot => "Potion Slot",
        PotionId::Block => "Block Potion",
        PotionId::Strength => "Strength Potion",
        PotionId::Dexterity => "Dexterity Potion",
        PotionId::Fire => "Fire Potion",
        PotionId::Explosive => "Explosive Potion",
        PotionId::Fear => "FearPotion",
        PotionId::Weak => "Weak Potion",
        PotionId::Attack => "AttackPotion",
        PotionId::Skill => "SkillPotion",
        PotionId::Power => "PowerPotion",
        PotionId::Blood => "BloodPotion",
        PotionId::Elixir => "ElixirPotion",
        PotionId::HeartOfIron => "HeartOfIron",
        PotionId::LiquidBronze => "LiquidBronze",
        PotionId::Duplication => "DuplicationPotion",
        PotionId::Energy => "Energy Potion",
        PotionId::Swift => "Swift Potion",
        PotionId::Colorless => "ColorlessPotion",
        PotionId::BlessingOfTheForge => "BlessingOfTheForge",
        PotionId::FruitJuice => "Fruit Juice",
        PotionId::Regen => "Regen Potion",
        PotionId::Speed => "SpeedPotion",
        PotionId::Steroid => "SteroidPotion",
        PotionId::Ancient => "Ancient Potion",
        PotionId::GamblersBrew => "GamblersBrew",
        PotionId::EssenceOfSteel => "EssenceOfSteel",
        PotionId::DistilledChaos => "DistilledChaos",
        PotionId::LiquidMemories => "LiquidMemories",
        PotionId::Cultist => "CultistPotion",
        PotionId::SneckoOil => "SneckoOil",
        PotionId::Fairy => "FairyPotion",
        PotionId::SmokeBomb => "SmokeBomb",
        PotionId::EntropicBrew => "EntropicBrew",
        PotionId::Focus => "FocusPotion",
        PotionId::PotionOfCapacity => "PotionOfCapacity",
        PotionId::EssenceOfDarkness => "EssenceOfDarkness",
    }
}

crate::string_id_serde!(EncounterId, sts_key, from_sts_key);

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MonsterId {
    Cultist,
    JawWorm,
    AcidSlimeS,
    AcidSlimeM,
    AcidSlimeL,
    SpikeSlimeS,
    SpikeSlimeM,
    SpikeSlimeL,
    LouseNormal,
    LouseDefensive,
    FungiBeast,
    SlaverBlue,
    SlaverRed,
    Looter,
    Mugger,
    BanditChild,
    BanditLeader,
    BanditBear,
    GremlinFat,
    GremlinTsundere,
    GremlinThief,
    GremlinWarrior,
    GremlinWizard,
    GremlinNob,
    GremlinLeader,
    Taskmaster,
    Lagavulin,
    Sentry,
    Hexaghost,
    TheGuardian,
    SlimeBoss,
    SpireShield,
    SpireSpear,
    CorruptHeart,
    Deca,
    Donu,
    SphericGuardian,
    Chosen,
    Centurion,
    Healer,
    SnakePlant,
    ShelledParasite,
    BronzeAutomaton,
    BronzeOrb,
    BookOfStabbing,
    Spiker,
    Exploder,
    Repulsor,
    Darkling,
    Transient,
    GiantHead,
    Nemesis,
    Reptomancer,
    Dagger,
    WrithingMass,
    SpireGrowth,
    AwakenedOne,
    TimeEater,
    Snecko,
    Byrd,
    Champ,
    OrbWalker,
    Maw,
    TheCollector,
    TorchHead,
    Unknown,
}

crate::string_id_map! {
    MonsterId,
    STS_IDS,
    sts_id,
    from_sts_id {
            MonsterId::Cultist => "Cultist",
            MonsterId::JawWorm => "JawWorm",
            MonsterId::AcidSlimeS => "AcidSlime_S",
            MonsterId::AcidSlimeM => "AcidSlime_M",
            MonsterId::AcidSlimeL => "AcidSlime_L",
            MonsterId::SpikeSlimeS => "SpikeSlime_S",
            MonsterId::SpikeSlimeM => "SpikeSlime_M",
            MonsterId::SpikeSlimeL => "SpikeSlime_L",
            MonsterId::LouseNormal => "FuzzyLouseNormal",
            MonsterId::LouseDefensive => "FuzzyLouseDefensive",
            MonsterId::FungiBeast => "FungiBeast",
            MonsterId::SlaverBlue => "SlaverBlue",
            MonsterId::SlaverRed => "SlaverRed",
            MonsterId::Looter => "Looter",
            MonsterId::Mugger => "Mugger",
            MonsterId::BanditChild => "BanditChild",
            MonsterId::BanditLeader => "BanditLeader",
            MonsterId::BanditBear => "BanditBear",
            MonsterId::GremlinFat => "GremlinFat",
            MonsterId::GremlinTsundere => "GremlinTsundere",
            MonsterId::GremlinThief => "GremlinThief",
            MonsterId::GremlinWarrior => "GremlinWarrior",
            MonsterId::GremlinWizard => "GremlinWizard",
            MonsterId::GremlinNob => "GremlinNob",
            MonsterId::GremlinLeader => "GremlinLeader",
            MonsterId::Taskmaster => "SlaverBoss",
            MonsterId::Lagavulin => "Lagavulin",
            MonsterId::Sentry => "Sentry",
            MonsterId::Hexaghost => "Hexaghost",
            MonsterId::TheGuardian => "TheGuardian",
            MonsterId::SlimeBoss => "SlimeBoss",
            MonsterId::SpireShield => "SpireShield",
            MonsterId::SpireSpear => "SpireSpear",
            MonsterId::CorruptHeart => "CorruptHeart",
            MonsterId::Deca => "Deca",
            MonsterId::Donu => "Donu",
            MonsterId::SphericGuardian => "SphericGuardian",
            MonsterId::Chosen => "Chosen",
            MonsterId::Centurion => "Centurion",
            MonsterId::Healer => "Healer",
            MonsterId::SnakePlant => "SnakePlant",
            MonsterId::ShelledParasite => "Shelled Parasite",
            MonsterId::BronzeAutomaton => "BronzeAutomaton",
            MonsterId::BronzeOrb => "BronzeOrb",
            MonsterId::BookOfStabbing => "BookOfStabbing",
            MonsterId::Spiker => "Spiker",
            MonsterId::Exploder => "Exploder",
            MonsterId::Repulsor => "Repulsor",
            MonsterId::Darkling => "Darkling",
            MonsterId::Transient => "Transient",
            MonsterId::GiantHead => "GiantHead",
            MonsterId::Nemesis => "Nemesis",
            MonsterId::Reptomancer => "Reptomancer",
            MonsterId::Dagger => "Dagger",
            MonsterId::WrithingMass => "WrithingMass",
            MonsterId::SpireGrowth => "Serpent",
            MonsterId::AwakenedOne => "AwakenedOne",
            MonsterId::TimeEater => "TimeEater",
            MonsterId::Snecko => "Snecko",
            MonsterId::Byrd => "Byrd",
            MonsterId::Champ => "Champ",
            MonsterId::OrbWalker => "Orb Walker",
            MonsterId::Maw => "Maw",
            MonsterId::TheCollector => "TheCollector",
            MonsterId::TorchHead => "TorchHead",
            MonsterId::Unknown => "Unknown",
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum EncounterId {
    Cultist,
    JawWorm,
    TwoLouse,
    SmallSlimes,
    BlueSlaver,
    GremlinGang,
    Looter,
    LargeSlime,
    LotsOfSlimes,
    ExordiumThugs,
    ExordiumWildlife,
    RedSlaver,
    ThreeLouse,
    TwoFungiBeasts,
    MushroomLair,
    GremlinNob,
    Lagavulin,
    ThreeSentries,
    Hexaghost,
    TheGuardian,
    SlimeBoss,
    ShieldAndSpear,
    CorruptHeart,
    DonuAndDeca,
    SphericGuardian,
    SphereAndTwoShapes,
    Chosen,
    CenturionAndHealer,
    SnakePlant,
    ShelledParasiteAndFungi,
    Automaton,
    BookOfStabbing,
    Slavers,
    ColosseumSlavers,
    ColosseumNobs,
    GremlinLeader,
    MaskedBandits,
    ThreeShapes,
    FourShapes,
    ThreeDarklings,
    Transient,
    GiantHead,
    Nemesis,
    Reptomancer,
    WrithingMass,
    SpireGrowth,
    JawWormHorde,
    AwakenedOne,
    TimeEater,
    TwoThieves,
    ShellParasite,
    SentryAndSphere,
    CultistAndChosen,
    ThreeCultists,
    Snecko,
    ThreeByrds,
    ChosenAndByrds,
    Champ,
    OrbWalker,
    Maw,
    Collector,
}

crate::string_id_map! {
    EncounterId,
    STS_KEYS,
    sts_key,
    from_sts_key {
EncounterId::Cultist => "Cultist",
EncounterId::JawWorm => "Jaw Worm",
EncounterId::TwoLouse => "2 Louse",
EncounterId::SmallSlimes => "Small Slimes",
EncounterId::BlueSlaver => "Blue Slaver",
EncounterId::GremlinGang => "Gremlin Gang",
EncounterId::Looter => "Looter",
EncounterId::LargeSlime => "Large Slime",
EncounterId::LotsOfSlimes => "Lots of Slimes",
EncounterId::ExordiumThugs => "Exordium Thugs",
EncounterId::ExordiumWildlife => "Exordium Wildlife",
EncounterId::RedSlaver => "Red Slaver",
EncounterId::ThreeLouse => "3 Louse",
EncounterId::TwoFungiBeasts => "2 Fungi Beasts",
EncounterId::MushroomLair => "The Mushroom Lair",
EncounterId::GremlinNob => "Gremlin Nob",
EncounterId::Lagavulin => "Lagavulin",
EncounterId::ThreeSentries => "3 Sentries",
EncounterId::Hexaghost => "Hexaghost" | "GHOST",
EncounterId::TheGuardian => "The Guardian" | "GUARDIAN",
EncounterId::SlimeBoss => "Slime Boss" | "SLIME",
EncounterId::ShieldAndSpear => "Shield and Spear",
EncounterId::CorruptHeart => "The Heart",
EncounterId::DonuAndDeca => "Donu and Deca" | "DONUT",
EncounterId::SphericGuardian => "Spheric Guardian",
EncounterId::SphereAndTwoShapes => "Sphere and 2 Shapes",
EncounterId::Chosen => "Chosen",
EncounterId::CenturionAndHealer => "Centurion and Healer",
EncounterId::SnakePlant => "Snake Plant",
EncounterId::ShelledParasiteAndFungi => "Shelled Parasite and Fungi",
EncounterId::Automaton => "Automaton" | "AUTOMATON",
EncounterId::BookOfStabbing => "Book of Stabbing",
EncounterId::Slavers => "Slavers",
EncounterId::ColosseumSlavers => "Colosseum Slavers",
EncounterId::ColosseumNobs => "Colosseum Nobs",
EncounterId::GremlinLeader => "Gremlin Leader",
EncounterId::MaskedBandits => "Masked Bandits",
EncounterId::ThreeShapes => "3 Shapes",
EncounterId::FourShapes => "4 Shapes",
EncounterId::ThreeDarklings => "3 Darklings",
EncounterId::Transient => "Transient",
EncounterId::GiantHead => "Giant Head",
EncounterId::Nemesis => "Nemesis",
EncounterId::Reptomancer => "Reptomancer",
EncounterId::WrithingMass => "Writhing Mass",
EncounterId::SpireGrowth => "Spire Growth",
EncounterId::JawWormHorde => "Jaw Worm Horde",
EncounterId::AwakenedOne => "Awakened One" | "CROW",
EncounterId::TimeEater => "Time Eater" | "WIZARD",
EncounterId::TwoThieves => "2 Thieves",
EncounterId::ShellParasite => "Shell Parasite",
EncounterId::SentryAndSphere => "Sentry and Sphere",
EncounterId::CultistAndChosen => "Cultist and Chosen",
EncounterId::ThreeCultists => "3 Cultists",
EncounterId::Snecko => "Snecko",
EncounterId::ThreeByrds => "3 Byrds",
EncounterId::ChosenAndByrds => "Chosen and Byrds",
EncounterId::Champ => "Champ" | "CHAMP",
EncounterId::OrbWalker => "Orb Walker",
EncounterId::Maw => "Maw",
EncounterId::Collector => "Collector" | "COLLECTOR",
    }
}

#[cfg(test)]
mod string_mapping_tests {
    use super::*;
    use std::collections::HashSet;

    macro_rules! assert_round_trip {
        ($type:ty, $table:ident, $to:ident, $from:ident) => {{
            let mut canonical = HashSet::new();
            for &(id, wire) in <$type>::$table {
                assert!(canonical.insert(wire), "duplicate canonical value {wire:?}");
                assert_eq!(id.$to(), wire);
                assert_eq!(<$type>::$from(wire), Some(id));
            }
        }};
    }

    #[test]
    fn generated_string_boundaries_round_trip_their_canonical_tables() {
        assert_round_trip!(Character, STS_NAMES, sts_name, from_sts_name);
        assert_round_trip!(RoomType, JAVA_CLASSES, java_class, from_java_class);
        assert_round_trip!(EventId, STS_IDS, sts_id, from_sts_id);
        assert_round_trip!(PotionId, STS_IDS, sts_id, from_sts_id);
        assert_round_trip!(MonsterId, STS_IDS, sts_id, from_sts_id);
        assert_round_trip!(EncounterId, STS_KEYS, sts_key, from_sts_key);
        assert_round_trip!(CardId, STS_IDS, sts_id, from_sts_id);
        assert_round_trip!(RelicId, STS_IDS, sts_id, from_sts_id);
        assert_eq!(RelicId::from_sts_id("Sacred Bark"), Some(RelicId::SacredBark));
    }
}
